Listen:
  # 管理页面 web server 地址，必填
  admin: "{env.APPListenAdmin|127.0.0.1:8080}"
  # api server 地址，可选，当为空或者和 admin 的值一样时，api 注册到 管理页面
  api: "{env.APPListenAPI|127.0.0.1:8081}"

# 数据目录，当为空时，默认会使用应用根目录下的 data 目录
#DataDir: "{env.AppDataDir}"

# 临时数据目录，当 RPCCache 使用 file 时，缓存内容会存储在此目录下
#TempDir: "{env.AppTempDir}"

# 运行模式，可选 debug，product
RunMode: "{env.RunMode|debug}"


Other:
  # 日志等级，可选值：DEBUG，INFO，WARN，ERROR
  LogLevel: "{env.LogLevel|DEBUG}"

  # 后台管理页面的地址，可选，默认为 /admin/
  AdminPath: {env.APPAdminPath|/admin/}

  # 加密秘钥，用于加密数据, 请一定修改，不使用默认值
  SecretKey: {env.APPSecretKey|f2f2aeedcc3e15852712a49234993392}

  # 将请求和响应内容打印存储到 log/rpcdump/ 目录中，可用于分析&观察请求数据，可选，默认为 false
  RPCDump: {env.APPRPCDump|true}

# 管理员列表，必填
Users:
  - Username: {env.APPUsername|admin}
    Password: {env.APPPassword|psw}

# 读取静态服务配置的文件名，可选
# 建议还是使用 web 页面配置，所有配置的内容都会加密存储，安全性更好
# 若文件不存在，会跳过
StaticAPIFile: {env.APPStaticAPIFile|static_api.yml}

