Listen:
  # 管理页面 web server 地址，必填
  admin: "{env.APPListenAdmin|127.0.0.1:8080}"
  # api server 地址，可选，当为空时，api 注册到 管理页面
  api: "{env.APPListenAPI|127.0.0.1:8081}"

# 数据目录，当为空时，默认会使用应用根目录下的 data 目录
#DataDir: "{env.AppDataDir}"

# 临时数据目录，当 RPCCache 使用 file 时，缓存内容会存储在此目录下
#TempDir: "{env.AppTempDir}"

# 运行模式，可选 debug，product
RunMode: "{env.RunMode|debug}"


Other:
  # 日志等级，可选值：DEBUG，INFO，WARN，ERROR
  LogLevel: "{env.LogLevel|DEBUG}"

  # 后台管理页面的地址，可选，默认为 /admin/
  AdminPath: {env.APPAdminPath|/admin/}

  # 加密秘钥，用于加密数据, 请一定修改，不使用默认值
  SecretKey: {env.APPSecretKey|f2f2aeedcc3e15852712a49234993392}

  # 管理页面的 HTTP 会话信息存储方式，可选 cookie,memory,file,kvdb
  # cookie: 存储到 http cookie 信息中
  # memory: 存储在内存中，应用重启后就丢失，管理页面需要重新登录
  # file: 存储在应用的 temp 目录的文件中，默认值
  # kvdb： 存储在 kv 数据引擎，详见下列 KVDB 配置
  Session: {env.APPSession|"cookie"}

  # 存储数据的 Key-Value DB 类型，必填，支持：
  # file：使用文件存储，存储在应用的 {DataDir}/xkv_db/ 目录下
  # memory：内存,应用重启后丢失
  # redis：使用 Redis，同时需要配置服务配置名称，配置位于 service 目录。如 redis:kv_rds
  KVDB: "{env.APPKVDB|file}"

  # 将请求和响应内容打印存储到 log/rpcdump/ 目录中，可用于分析&观察请求数据，可选，默认为 false
  RPCDump: {env.APPRPCDump|true}

# 管理员列表，必填
Users:
  - Username: {env.APPUsername|admin}
    Password: {env.APPPassword|psw}

# 读取静态服务配置的文件名，可选
# 建议还是使用 web 页面配置，所有配置的内容都会加密存储，安全性更好
# 若文件不存在，会跳过
StaticAPIFile: {env.APPStaticAPIFile|static_api.yml}

