// Code generated by anygo-encrypt-zip DO NOT EDIT.

//go:build release

package admin

import (
	_ "embed"
	"io/fs"

	"github.com/xanygo/anygo/ds/xsync"
	"github.com/xanygo/anygo/ds/xzip"
	"github.com/xanygo/anygo/xcodec"
)

//go:embed asset.ez
var _346b69b7f6fe703ea269901f900374fb []byte

var _346b69b7f6fe703ea269901f900374fbOnce = &xsync.OnceInit[fs.FS]{
	New: func() fs.FS {
		dz := &xcodec.AesOFB{
			Key: string([]byte{
				'6', 'b', '6', '5', 'f', '8', 'd', 'a',
				'a', 'e', '3', '2', '7', '0', 'd', '8',
				'3', '9', 'b', '4', '4', '3', 'c', 'd',
				'8', '3', '2', '7', 'a', '8', '0', '1',
			}),
		}
		rd := xzip.MustDecrypt(_346b69b7f6fe703ea269901f900374fb, dz)
		clear(_346b69b7f6fe703ea269901f900374fb)
		_346b69b7f6fe703ea269901f900374fb = nil
		return rd
	},
}

var files fs.FS = _346b69b7f6fe703ea269901f900374fbOnce.Load()
